# NLU HOSTAGE — ai_1_nlu_v3_600

Notebook ini hanya memakai modul training bersama. Semua cell legacy telah dihapus.

In [ ]:
from pathlib import Path
DATASET_FILENAME = "dataset_final3.csv"
NOTEBOOK_FOLDER = "ai_2_dataset_baru"
NOTEBOOK_DIR = Path.cwd()
if NOTEBOOK_DIR.name != NOTEBOOK_FOLDER:
    candidate = NOTEBOOK_DIR / NOTEBOOK_FOLDER
    if candidate.is_dir():
        NOTEBOOK_DIR = candidate
DATASET_PATH = NOTEBOOK_DIR / "data" / DATASET_FILENAME
print(f"Dataset aktif: {DATASET_PATH}")

In [ ]:
# MODUL BERSAMA: EDA + SVM + SVM TUNING + NB + NB TUNING + TRANSFORMER
from pathlib import Path
import sys

PROJECT_ROOT = Path(NOTEBOOK_DIR).parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from modules.nlu_eda import run_nlu_eda
from modules.nlu_training import (
    predict_intent as _predict_intent_shared,
    predict_transformer_intent as _predict_transformer_intent_shared,
    run_all_nlu_models,
    train_naive_bayes,
    train_naive_bayes_tuned,
    train_svm,
    train_svm_tuned,
    train_transformer,
)

MODEL_DIR = Path(NOTEBOOK_DIR) / "models"
# Kebijakan proyek: SVM/NB pada CPU, Transformer pada GPU CUDA.
CLASSICAL_DEVICE = "cpu"
TRANSFORMER_DEVICE = "cuda"
# Fine-tuning: seluruh bobot IndoBERT dilatih. Epoch adalah batas maksimum.
TRANSFORMER_EPOCHS = 12
TRANSFORMER_OPTIONS = {
    "learning_rates": (1e-5, 2e-5, 3e-5),  # pilih hanya dari validation macro-F1
    "validation_size": 0.15,  # train/validation/test sekitar 65/15/20
    "batch_size": 8,
    "eval_batch_size": 16,
    "gradient_accumulation_steps": 2,  # effective batch 16 pada satu GPU
    "max_length": 128,
    "weight_decay": 0.01,
    "warmup_ratio": 0.1,
    "lr_scheduler_type": "linear",
    "dropout": 0.1,
    "label_smoothing_factor": 0.0,
    "max_grad_norm": 1.0,
    "early_stopping_patience": 3,
    "early_stopping_threshold": 0.001,
    "gradient_checkpointing": False,  # aktifkan jika memori GPU tidak cukup
}


def run_eda(plot=True):
    return run_nlu_eda(DATASET_PATH, plot=plot)

def train_svm_model():
    return train_svm(DATASET_PATH, MODEL_DIR)

def train_svm_tuned_model():
    return train_svm_tuned(DATASET_PATH, MODEL_DIR)

def train_naive_bayes_model():
    return train_naive_bayes(DATASET_PATH, MODEL_DIR)

def train_naive_bayes_tuned_model():
    return train_naive_bayes_tuned(DATASET_PATH, MODEL_DIR)

def train_transformer_model(epochs=None, **overrides):
    options = {**TRANSFORMER_OPTIONS, **overrides}
    # Untuk satu LR: train_transformer_model(learning_rates=None, learning_rate=2e-5)
    return train_transformer(
        DATASET_PATH, MODEL_DIR,
        epochs=TRANSFORMER_EPOCHS if epochs is None else epochs,
        device=TRANSFORMER_DEVICE, **options,
    )

def predict_intent(text, model_filename=None):
    return _predict_intent_shared(text, MODEL_DIR, model_filename)

def predict_transformer_intent(text):
    return _predict_transformer_intent_shared(text, MODEL_DIR, device=TRANSFORMER_DEVICE)

# Tiga intent dataset Janice; dipakai juga untuk evaluasi setelah training.
HOSTAGE_TEST_CASES = [
    ("offend", "B kena Gag Order ketika mulai ditanya alibinya, menurutku itu pola Hitman."),
    ("defend", "Aku bukan Hitman. Tuduhan itu tidak punya bukti dari chat publik."),
    ("defend", "Aku Spy dan semalam Guard Raka, jadi jangan curigai dia."),
    ("neutral", "Stalker, kamu Peek siapa semalam dan apa hasil yang kamu lihat?"),
    ("offend", "Jangan hanya fokus ke aku; cek D yang ceritanya berubah setiap ditanya."),
    ("offend", "Vote C saja, dia paling diuntungkan ketika seseorang mendadak diam."),
    ("defend", "Klaimku Civilian, jadi aku memang tidak memiliki aksi malam."),
    ("neutral", "Malam ini chat terkunci, kita lanjut diskusi setelah fase pagi."),
    ("offend", "A selalu menghindar saat kita tanya kenapa dia menuduh tanpa bukti."),
    ("defend", "Diamku bukan pengakuan; aku masih bisa menjelaskan alibiku di fase siang."),
]

def run_hostage_test_suite(model_filename=None):
    correct = 0
    for expected, chat in HOSTAGE_TEST_CASES:
        predicted, confidence = predict_intent(chat, model_filename)
        correct += predicted == expected
        print(f"{expected:12} | prediksi={predicted:12} | confidence={confidence:6.2f}% | {chat}")
    print(f"\nCocok: {correct}/{len(HOSTAGE_TEST_CASES)}")

print("Modul NLU siap. Jalankan: run_eda(), train_svm_model(), train_svm_tuned_model(),")
print("train_naive_bayes_model(), train_naive_bayes_tuned_model(), atau train_transformer_model().")
print("Mode training aktif: CPU untuk SVM/Naive Bayes, GPU CUDA untuk Transformer.")
print("Model tersimpan terpisah; prediksi default memprioritaskan SVM tuned.")

In [ ]:
run_eda()

In [ ]:
# Muat ulang modul agar kernel memakai perubahan kode terbaru.
import importlib
import modules.nlu_training as nlu_training
nlu_training = importlib.reload(nlu_training)
run_all_nlu_models = nlu_training.run_all_nlu_models

# Jalankan baseline CPU dan fine-tuning IndoBERT CUDA; tuning SVM/NB opsional.
RUN_TRANSFORMER = True
RUN_TUNING = False  # khusus grid search SVM/NB; IndoBERT memakai TRANSFORMER_OPTIONS
artifacts, hasil_training, hasil_manual_test = run_all_nlu_models(
    DATASET_PATH, MODEL_DIR,
    run_transformer=RUN_TRANSFORMER,
    run_tuning=RUN_TUNING,
    transformer_epochs=TRANSFORMER_EPOCHS,
    transformer_device=TRANSFORMER_DEVICE,
    transformer_options=TRANSFORMER_OPTIONS,
    benchmark_tests=HOSTAGE_TEST_CASES,
)
print('RINGKASAN EVALUASI HOLDOUT:')
display(hasil_training)
print('RINGKASAN 10 CHAT UJI:')
display(hasil_manual_test)

# Riwayat loss dan validation macro-F1 per epoch; test tidak dipakai memilih model.
if "IndoBERT Transformer" in artifacts:
    import pandas as pd
    transformer_summary = artifacts["IndoBERT Transformer"]["artifact"]["training_summary"]
    display(pd.DataFrame([
        {k: v for k, v in trial.items() if k not in {"history", "best_checkpoint"}}
        for trial in transformer_summary["trials"]
    ]))
    for trial in transformer_summary["trials"]:
        print(f"Learning rate: {trial['learning_rate']:g}")
        display(pd.DataFrame(trial["history"]))

In [3]:
# TUNING SVM DAN NAIVE BAYES
# Cell ini dapat dijalankan langsung dari folder proyek atau subfoldernya.
from pathlib import Path
import sys
import importlib
from time import perf_counter

_current_dir = Path.cwd().resolve()
PROJECT_ROOT = next((
    folder for folder in (_current_dir, *_current_dir.parents)
    if (folder / "modules" / "nlu_training.py").is_file()
    and (folder / "ai_2_dataset_baru" / "data" / "dataset_final3.csv").is_file()
), None)
if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "Folder proyek tidak ditemukan. Buka notebook dari workspace prethesis."
    )
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

NOTEBOOK_DIR = PROJECT_ROOT / "ai_2_dataset_baru"
DATASET_PATH = NOTEBOOK_DIR / "data" / "dataset_final3.csv"
MODEL_DIR = NOTEBOOK_DIR / "models"
HOSTAGE_TEST_CASES = [
    ("offend", "B kena Gag Order ketika mulai ditanya alibinya, menurutku itu pola Hitman."),
    ("defend", "Aku bukan Hitman. Tuduhan itu tidak punya bukti dari chat publik."),
    ("defend", "Aku Spy dan semalam Guard Raka, jadi jangan curigai dia."),
    ("neutral", "Stalker, kamu Peek siapa semalam dan apa hasil yang kamu lihat?"),
    ("offend", "Jangan hanya fokus ke aku; cek D yang ceritanya berubah setiap ditanya."),
    ("offend", "Vote C saja, dia paling diuntungkan ketika seseorang mendadak diam."),
    ("defend", "Klaimku Civilian, jadi aku memang tidak memiliki aksi malam."),
    ("neutral", "Malam ini chat terkunci, kita lanjut diskusi setelah fase pagi."),
    ("offend", "A selalu menghindar saat kita tanya kenapa dia menuduh tanpa bukti."),
    ("defend", "Diamku bukan pengakuan; aku masih bisa menjelaskan alibiku di fase siang."),
]

import pandas as pd
from IPython.display import display
import modules.nlu_training as nlu_training

nlu_training = importlib.reload(nlu_training)
artifacts_tuning = {}
ringkasan_tuning = []
chat_tuning = []

for nama, trainer in [
    ("SVM tuned", nlu_training.train_svm_tuned),
    ("Naive Bayes tuned", nlu_training.train_naive_bayes_tuned),
]:
    print(f"\nMENJALANKAN: {nama}", flush=True)
    mulai = perf_counter()
    hasil = trainer(DATASET_PATH, MODEL_DIR)
    durasi = perf_counter() - mulai
    artifacts_tuning[nama] = hasil
    metrik = hasil["metrics"]
    ringkasan_tuning.append({
        "model": nama,
        "accuracy_holdout": metrik["accuracy"],
        "macro_f1_holdout": metrik["f1_macro"],
        "weighted_f1_holdout": metrik["f1_weighted"],
        "macro_f1_cv": hasil["cv_f1_macro"],
        "waktu_detik": round(durasi, 1),
    })
    print("Parameter terbaik:", hasil["best_params"])
    for expected, chat in HOSTAGE_TEST_CASES:
        predicted, confidence = nlu_training.predict_intent(
            chat, MODEL_DIR, filename=Path(hasil["model_path"]).name,
        )
        chat_tuning.append({
            "model": nama, "chat": chat, "expected": expected,
            "predicted": predicted, "confidence_persen": confidence,
            "benar": predicted == expected,
        })

hasil_training_tuning = pd.DataFrame(ringkasan_tuning)
hasil_manual_test_tuning = pd.DataFrame(chat_tuning)
print("\nRINGKASAN EVALUASI HOLDOUT TUNING:")
display(hasil_training_tuning)
print("\nHASIL CHAT UJI TUNING:")
display(hasil_manual_test_tuning)
display(hasil_manual_test_tuning.groupby("model")["benar"].agg(
    jumlah_benar="sum", jumlah_chat="count", akurasi="mean",
).reset_index())

MENJALANKAN: SVM tuned
Memulai SVM Grid Search pada train set...
Fitting 5 folds for each of 720 candidates, totalling 3600 fits
Parameter SVM terbaik: {'svm__C': 1.5, 'svm__class_weight': 'balanced', 'tfidf__analyzer': 'word', 'tfidf__max_df': 0.95, 'tfidf__min_df': 1, 'tfidf__ngram_range': (1, 3), 'tfidf__sublinear_tf': False}
Macro-F1 CV terbaik: 0.8420

--- Evaluasi SVM tuned (holdout test set) ---
Accuracy    : 0.8625
Macro F1    : 0.8395
Weighted F1 : 0.8627
              precision    recall  f1-score   support

      defend       0.74      0.76      0.75       188
     neutral       0.87      0.88      0.87       419
      offend       0.90      0.89      0.89       513

    accuracy                           0.86      1120
   macro avg       0.84      0.84      0.84      1120
weighted avg       0.86      0.86      0.86      1120

Model tersimpan: C:\Users\andyc\Documents\a_skripsi\training\prethesis\ai_2_dataset_baru\models\intent_classifier_svm_tuned.pkl
Parameter terbaik: {'svm__C': 1.5, 'svm__class_weight': 'balanced', 'tfidf__analyzer': 'word', 'tfidf__max_df': 0.95, 'tfidf__min_df': 1, 'tfidf__ngram_range': (1, 3), 'tfidf__sublinear_tf': False}

MENJALANKAN: Naive Bayes tuned
Memulai Naive Bayes Grid Search pada train set...
Fitting 5 folds for each of 1920 candidates, totalling 9600 fits
Parameter NB terbaik: {'nb__alpha': 0.1, 'nb__fit_prior': False, 'tfidf__max_df': 0.95, 'tfidf__min_df': 1, 'tfidf__ngram_range': (1, 2), 'tfidf__norm': 'l2', 'tfidf__sublinear_tf': False, 'tfidf__use_idf': False}
Macro-F1 CV terbaik: 0.8171

--- Evaluasi Naive Bayes tuned (holdout test set) ---
Accuracy    : 0.8455
Macro F1    : 0.8169
Weighted F1 : 0.8458
              precision    recall  f1-score   support

      defend       0.70      0.71      0.70       188
     neutral       0.86      0.88      0.87       419
      offend       0.89      0.87      0.88       513

    accuracy                           0.85      1120
   macro avg       0.82      0.82      0.82      1120
weighted avg       0.85      0.85      0.85      1120

Model tersimpan: C:\Users\andyc\Documents\a_skripsi\training\prethesis\ai_2_dataset_baru\models\intent_classifier_nb_tuned.pkl
Parameter terbaik: {'nb__alpha': 0.1, 'nb__fit_prior': False, 'tfidf__max_df': 0.95, 'tfidf__min_df': 1, 'tfidf__ngram_range': (1, 2), 'tfidf__norm': 'l2', 'tfidf__sublinear_tf': False, 'tfidf__use_idf': False}

RINGKASAN EVALUASI HOLDOUT TUNING:

,model,accuracy_holdout,macro_f1_holdout,weighted_f1_holdout,macro_f1_cv,waktu_detik
0,SVM tuned,0.8625,0.8395,0.8627,0.8420,195.2
1,Naive Bayes tuned,0.8455,0.8169,0.8458,0.8171,383.5

HASIL CHAT UJI TUNING:

,model,chat,expected,predicted,confidence_persen,benar
0,SVM tuned,B kena Gag Order ketika mulai ditanya alibinya...,offend,offend,98.42,True
1,SVM tuned,Aku bukan Hitman. Tuduhan itu tidak punya bukt...,defend,defend,95.82,True
2,SVM tuned,"Aku Spy dan semalam Guard Raka, jadi jangan cu...",defend,defend,85.40,True
3,SVM tuned,"Stalker, kamu Peek siapa semalam dan apa hasil...",neutral,neutral,99.04,True
4,SVM tuned,Jangan hanya fokus ke aku; cek D yang ceritany...,offend,offend,70.46,True
5,SVM tuned,"Vote C saja, dia paling diuntungkan ketika ses...",offend,offend,99.23,True
6,SVM tuned,"Klaimku Civilian, jadi aku memang tidak memili...",defend,neutral,68.89,False
7,SVM tuned,"Malam ini chat terkunci, kita lanjut diskusi s...",neutral,neutral,87.81,True
8,SVM tuned,A selalu menghindar saat kita tanya kenapa dia...,offend,offend,99.65,True
9,SVM tuned,Diamku bukan pengakuan; aku masih bisa menjela...,defend,neutral,54.73,False
10,Naive Bayes tuned,B kena Gag Order ketika mulai ditanya alibinya...,offend,offend,98.62,True
11,Naive Bayes tuned,Aku bukan Hitman. Tuduhan itu tidak punya bukt...,defend,defend,88.57,True
12,Naive Bayes tuned,"Aku Spy dan semalam Guard Raka, jadi jangan cu...",defend,neutral,57.62,False
13,Naive Bayes tuned,"Stalker, kamu Peek siapa semalam dan apa hasil...",neutral,neutral,99.10,True
14,Naive Bayes tuned,Jangan hanya fokus ke aku; cek D yang ceritany...,offend,offend,88.91,True
15,Naive Bayes tuned,"Vote C saja, dia paling diuntungkan ketika ses...",offend,offend,96.21,True
16,Naive Bayes tuned,"Klaimku Civilian, jadi aku memang tidak memili...",defend,neutral,55.44,False
17,Naive Bayes tuned,"Malam ini chat terkunci, kita lanjut diskusi s...",neutral,neutral,90.69,True
18,Naive Bayes tuned,A selalu menghindar saat kita tanya kenapa dia...,offend,offend,99.52,True
19,Naive Bayes tuned,Diamku bukan pengakuan; aku masih bisa menjela...,defend,neutral,55.95,False

               model  jumlah_benar  jumlah_chat  akurasi
0  Naive Bayes tuned             7           10      0.7
1          SVM tuned             8           10      0.8

In [2]:
# TUNING OPTUNA: NAIVE BAYES DAN SVM
# Cell ini dapat dijalankan langsung dari folder proyek atau subfoldernya.
from pathlib import Path
import sys
import importlib
from time import perf_counter

_current_dir = Path.cwd().resolve()
PROJECT_ROOT = next((
    folder for folder in (_current_dir, *_current_dir.parents)
    if (folder / "modules" / "nlu_training.py").is_file()
    and (folder / "ai_2_dataset_baru" / "data" / "dataset_final3.csv").is_file()
), None)
if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "Folder proyek tidak ditemukan. Buka notebook dari workspace prethesis."
    )
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

NOTEBOOK_DIR = PROJECT_ROOT / "ai_2_dataset_baru"
DATASET_PATH = NOTEBOOK_DIR / "data" / "dataset_final3.csv"
MODEL_DIR = NOTEBOOK_DIR / "models"
HOSTAGE_TEST_CASES = [
    ("offend", "B kena Gag Order ketika mulai ditanya alibinya, menurutku itu pola Hitman."),
    ("defend", "Aku bukan Hitman. Tuduhan itu tidak punya bukti dari chat publik."),
    ("defend", "Aku Spy dan semalam Guard Raka, jadi jangan curigai dia."),
    ("neutral", "Stalker, kamu Peek siapa semalam dan apa hasil yang kamu lihat?"),
    ("offend", "Jangan hanya fokus ke aku; cek D yang ceritanya berubah setiap ditanya."),
    ("offend", "Vote C saja, dia paling diuntungkan ketika seseorang mendadak diam."),
    ("defend", "Klaimku Civilian, jadi aku memang tidak memiliki aksi malam."),
    ("neutral", "Malam ini chat terkunci, kita lanjut diskusi setelah fase pagi."),
    ("offend", "A selalu menghindar saat kita tanya kenapa dia menuduh tanpa bukti."),
    ("defend", "Diamku bukan pengakuan; aku masih bisa menjelaskan alibiku di fase siang."),
]

import pandas as pd
from IPython.display import display
import modules.nlu_training as nlu_training

nlu_training = importlib.reload(nlu_training)
OPTUNA_TRIALS = 50  # jumlah trial per model; ubah sesuai waktu eksperimen
OPTUNA_CV_FOLDS = 5
OPTUNA_TIMEOUT = None  # batas pencarian per model (detik), atau None
OPTUNA_N_JOBS = -1  # paralel fold CV; trial Optuna tetap berurutan

artifacts_optuna = {}
ringkasan_optuna = []
chat_optuna = []

for nama, trainer in [
    ("Naive Bayes Optuna", nlu_training.train_naive_bayes_optuna),
    ("SVM Optuna", nlu_training.train_svm_optuna),
]:
    print(f"\nMENJALANKAN: {nama}", flush=True)
    mulai = perf_counter()
    hasil = trainer(
        DATASET_PATH, MODEL_DIR, n_trials=OPTUNA_TRIALS,
        cv_folds=OPTUNA_CV_FOLDS, timeout=OPTUNA_TIMEOUT, n_jobs=OPTUNA_N_JOBS,
    )
    durasi = perf_counter() - mulai
    artifacts_optuna[nama] = hasil
    metrik = hasil["metrics"]
    ringkasan_optuna.append({
        "model": nama,
        "accuracy_holdout": metrik["accuracy"],
        "macro_f1_holdout": metrik["f1_macro"],
        "weighted_f1_holdout": metrik["f1_weighted"],
        "macro_f1_cv": hasil["cv_f1_macro"],
        "std_f1_cv": hasil["cv_std"],
        "jumlah_trial": len(hasil["study"].trials),
        "waktu_detik": round(durasi, 1),
    })
    print("Parameter terbaik:", hasil["best_params"])
    print("Riwayat eksperimen:", hasil["run_dir"])
    for expected, chat in HOSTAGE_TEST_CASES:
        predicted, confidence = nlu_training.predict_intent(
            chat, MODEL_DIR, filename=Path(hasil["model_path"]).name,
        )
        chat_optuna.append({
            "model": nama, "chat": chat, "expected": expected,
            "predicted": predicted, "confidence_persen": confidence,
            "benar": predicted == expected,
        })

hasil_training_optuna = pd.DataFrame(ringkasan_optuna)
hasil_manual_test_optuna = pd.DataFrame(chat_optuna)
print("\nRINGKASAN EVALUASI HOLDOUT OPTUNA:")
display(hasil_training_optuna)
print("\nHASIL CHAT UJI OPTUNA:")
display(hasil_manual_test_optuna)
display(hasil_manual_test_optuna.groupby("model")["benar"].agg(
    jumlah_benar="sum", jumlah_chat="count", akurasi="mean",
).reset_index())

MENJALANKAN: Naive Bayes Optuna

c:\Users\andyc\Documents\a_skripsi\training\prethesis\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2026-09-24 14:10:40,320] A new study created in memory with name: nb_macro_f1

Optuna NB: 50 trial, 5 fold, macro-F1.

[I 2026-09-24 14:10:42,937] Trial 0 finished with value: 0.8166103191825929 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': False, 'norm': 'l1', 'alpha': 0.030803400529839688, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:44,981] Trial 1 finished with value: 0.8042483681730094 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': False, 'norm': None, 'alpha': 0.012790390175145836, 'fit_prior': True}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:47,108] Trial 2 finished with value: 0.6391091559441071 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l1', 'alpha': 0.33456742136968215, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:48,814] Trial 3 finished with value: 0.7853102417146627 and parameters: {'word_ngram_max': 1, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': False, 'norm': None, 'alpha': 0.042109711053281526, 'fit_prior': True}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:48,937] Trial 4 finished with value: 0.804349376947704 and parameters: {'word_ngram_max': 2, 'min_df': 2, 'max_df': 1.0, 'sublinear_tf': True, 'use_idf': False, 'norm': None, 'alpha': 0.014803996190233563, 'fit_prior': True}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:49,018] Trial 5 finished with value: 0.7534956870628041 and parameters: {'word_ngram_max': 1, 'min_df': 1, 'max_df': 1.0, 'sublinear_tf': True, 'use_idf': True, 'norm': None, 'alpha': 0.19566613546446426, 'fit_prior': True}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:49,099] Trial 6 finished with value: 0.5835800262380422 and parameters: {'word_ngram_max': 1, 'min_df': 2, 'max_df': 1.0, 'sublinear_tf': False, 'use_idf': True, 'norm': 'l1', 'alpha': 0.015036026469597834, 'fit_prior': True}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:49,170] Trial 7 finished with value: 0.7855202823925882 and parameters: {'word_ngram_max': 1, 'min_df': 2, 'max_df': 0.95, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l2', 'alpha': 0.09611426142207997, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:49,314] Trial 8 finished with value: 0.5568453566220328 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 1.0, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l1', 'alpha': 0.037962833053422164, 'fit_prior': True}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:49,406] Trial 9 finished with value: 0.7817521906838012 and parameters: {'word_ngram_max': 1, 'min_df': 1, 'max_df': 1.0, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l2', 'alpha': 0.5656002335993312, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:49,544] Trial 10 finished with value: 0.6590464049821326 and parameters: {'word_ngram_max': 2, 'min_df': 2, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': True, 'norm': 'l1', 'alpha': 1.6160741196373223, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:49,668] Trial 11 finished with value: 0.8068491980311366 and parameters: {'word_ngram_max': 2, 'min_df': 2, 'max_df': 1.0, 'sublinear_tf': False, 'use_idf': False, 'norm': None, 'alpha': 0.03379212018720982, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:49,805] Trial 12 finished with value: 0.8072161163620029 and parameters: {'word_ngram_max': 2, 'min_df': 2, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': False, 'norm': None, 'alpha': 0.04439181167047794, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:49,942] Trial 13 finished with value: 0.8068281692070688 and parameters: {'word_ngram_max': 2, 'min_df': 2, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': False, 'norm': 'l1', 'alpha': 0.08679513966372333, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:50,102] Trial 14 finished with value: 0.8116093744061669 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': True, 'norm': 'l2', 'alpha': 0.08551336851179224, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:50,258] Trial 15 finished with value: 0.8106422440914424 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': True, 'norm': 'l2', 'alpha': 0.09836747757222462, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:50,417] Trial 16 finished with value: 0.8130341324887518 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': True, 'norm': 'l2', 'alpha': 0.2113441358101484, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:50,596] Trial 17 finished with value: 0.7366980818539487 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': True, 'norm': 'l2', 'alpha': 1.1787490126770288, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:50,766] Trial 18 finished with value: 0.7584830338038617 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': True, 'norm': 'l1', 'alpha': 0.20896650201621217, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:50,936] Trial 19 finished with value: 0.7632817182243061 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': True, 'norm': 'l2', 'alpha': 0.7655684786351856, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:51,083] Trial 20 finished with value: 0.8053748411463962 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': True, 'norm': 'l2', 'alpha': 0.02406971621343383, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:51,230] Trial 21 finished with value: 0.8110347367655715 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': True, 'norm': 'l2', 'alpha': 0.15504000399281578, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:51,381] Trial 22 finished with value: 0.8085193302707385 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': True, 'norm': 'l2', 'alpha': 0.0612416099570226, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:51,540] Trial 23 finished with value: 0.8105566397434032 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': True, 'norm': 'l2', 'alpha': 0.3111148842832147, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:51,699] Trial 24 finished with value: 0.805549385318397 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': True, 'norm': 'l2', 'alpha': 0.02318390879080057, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:51,867] Trial 25 finished with value: 0.7852700989319839 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': True, 'norm': 'l1', 'alpha': 0.1283750124365106, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:51,953] Trial 26 finished with value: 0.7697095887955444 and parameters: {'word_ngram_max': 1, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': True, 'norm': 'l2', 'alpha': 0.059219499748531385, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:52,113] Trial 27 finished with value: 0.716237197867897 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': True, 'norm': 'l1', 'alpha': 0.35415991235979816, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:52,274] Trial 28 finished with value: 0.8154772884012906 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': False, 'norm': 'l2', 'alpha': 0.0755946692421017, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:52,472] Trial 29 finished with value: 0.5678753540946553 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': False, 'norm': 'l1', 'alpha': 0.023948043483017427, 'fit_prior': True}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:52,642] Trial 30 finished with value: 0.8119411232802731 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': False, 'norm': 'l2', 'alpha': 0.054876691499280136, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:52,816] Trial 31 finished with value: 0.8146416260489204 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': False, 'norm': 'l2', 'alpha': 0.06679513347141897, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:52,996] Trial 32 finished with value: 0.8162529637806676 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': False, 'norm': 'l2', 'alpha': 0.1252604650581591, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:53,177] Trial 33 finished with value: 0.814721673689235 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'use_idf': False, 'norm': 'l2', 'alpha': 0.12929913450843375, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:53,359] Trial 34 finished with value: 0.8154836087367576 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l2', 'alpha': 0.1371653467463829, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:53,530] Trial 35 finished with value: 0.8018769396342552 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': True, 'use_idf': False, 'norm': None, 'alpha': 0.01013749055869935, 'fit_prior': True}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:53,616] Trial 36 finished with value: 0.7575566182771101 and parameters: {'word_ngram_max': 1, 'min_df': 1, 'max_df': 1.0, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l1', 'alpha': 0.3072748958390229, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:53,775] Trial 37 finished with value: 0.754623041255911 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l2', 'alpha': 0.1671828384912368, 'fit_prior': True}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:53,873] Trial 38 finished with value: 0.7823864147902869 and parameters: {'word_ngram_max': 1, 'min_df': 1, 'max_df': 1.0, 'sublinear_tf': True, 'use_idf': False, 'norm': None, 'alpha': 0.027888236715872587, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:54,021] Trial 39 finished with value: 0.8063392718645703 and parameters: {'word_ngram_max': 2, 'min_df': 2, 'max_df': 0.95, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l2', 'alpha': 0.01733849884520033, 'fit_prior': True}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:54,118] Trial 40 finished with value: 0.7839468469787209 and parameters: {'word_ngram_max': 1, 'min_df': 1, 'max_df': 1.0, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l1', 'alpha': 0.11434281254852716, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:54,269] Trial 41 finished with value: 0.8149162306531543 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l2', 'alpha': 0.13519116510894297, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:54,417] Trial 42 finished with value: 0.8138994513960796 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l2', 'alpha': 0.07291036701650354, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:54,597] Trial 43 finished with value: 0.8134101356929136 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l2', 'alpha': 0.046180593137606064, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:54,756] Trial 44 finished with value: 0.8025485286682063 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l2', 'alpha': 0.2329984943935139, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:54,904] Trial 45 finished with value: 0.8077141733526518 and parameters: {'word_ngram_max': 2, 'min_df': 2, 'max_df': 0.95, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l2', 'alpha': 0.1574059454324881, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:55,088] Trial 46 finished with value: 0.8101015072101099 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': True, 'use_idf': False, 'norm': None, 'alpha': 0.03318586891800219, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:55,260] Trial 47 finished with value: 0.5168387966456908 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 1.0, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l1', 'alpha': 0.41112087260988706, 'fit_prior': True}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:55,346] Trial 48 finished with value: 0.7855451098873509 and parameters: {'word_ngram_max': 1, 'min_df': 2, 'max_df': 0.95, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l2', 'alpha': 0.10388179781973647, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.
[I 2026-09-24 14:10:55,509] Trial 49 finished with value: 0.8156135199637408 and parameters: {'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': True, 'use_idf': False, 'norm': 'l2', 'alpha': 0.07744951493273398, 'fit_prior': False}. Best is trial 0 with value: 0.8166103191825929.

Parameter Optuna terbaik: {'tfidf__analyzer': 'word', 'tfidf__ngram_range': (1, 2), 'tfidf__min_df': 1, 'tfidf__max_df': 0.95, 'tfidf__sublinear_tf': False, 'tfidf__use_idf': False, 'tfidf__norm': 'l1', 'nb__alpha': 0.030803400529839688, 'nb__fit_prior': False}
Macro-F1 CV terbaik: 0.8166

--- Evaluasi NB Optuna (holdout test set) ---
Accuracy    : 0.8473
Macro F1    : 0.8171
Weighted F1 : 0.8468
              precision    recall  f1-score   support

      defend       0.71      0.69      0.70       188
     neutral       0.86      0.88      0.87       419
      offend       0.88      0.88      0.88       513

    accuracy                           0.85      1120
   macro avg       0.82      0.82      0.82      1120
weighted avg       0.85      0.85      0.85      1120

Model tersimpan: C:\Users\andyc\Documents\a_skripsi\training\prethesis\ai_2_dataset_baru\models\intent_classifier_nb_optuna.pkl
Parameter terbaik: {'tfidf__analyzer': 'word', 'tfidf__ngram_range': (1, 2), 'tfidf__min_df': 1, 'tfidf__max_df': 0.95, 'tfidf__sublinear_tf': False, 'tfidf__use_idf': False, 'tfidf__norm': 'l1', 'nb__alpha': 0.030803400529839688, 'nb__fit_prior': False}
Riwayat eksperimen: C:\Users\andyc\Documents\a_skripsi\training\prethesis\ai_2_dataset_baru\models\optuna_results\nb_esx5pht6

MENJALANKAN: SVM Optuna

[I 2026-09-24 14:10:56,172] A new study created in memory with name: svm_macro_f1

Optuna SVM: 50 trial, 5 fold, macro-F1.

[I 2026-09-24 14:10:57,732] Trial 0 finished with value: 0.8189320381325503 and parameters: {'analyzer': 'char_wb', 'char_ngram_max': 5, 'min_df': 1, 'max_df': 1.0, 'sublinear_tf': False, 'C': 0.2684866893982092, 'class_weight': None}. Best is trial 0 with value: 0.8189320381325503.
[I 2026-09-24 14:10:58,475] Trial 1 finished with value: 0.8302693479362567 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 1.2144894192131561, 'class_weight': None}. Best is trial 1 with value: 0.8302693479362567.
[I 2026-09-24 14:11:00,156] Trial 2 finished with value: 0.8183347150389746 and parameters: {'analyzer': 'char_wb', 'char_ngram_max': 6, 'min_df': 1, 'max_df': 1.0, 'sublinear_tf': True, 'C': 0.350712454605835, 'class_weight': None}. Best is trial 1 with value: 0.8302693479362567.
[I 2026-09-24 14:11:02,758] Trial 3 finished with value: 0.8047091281169247 and parameters: {'analyzer': 'char_wb', 'char_ngram_max': 6, 'min_df': 2, 'max_df': 1.0, 'sublinear_tf': True, 'C': 7.19963185976389, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8302693479362567.
[I 2026-09-24 14:11:03,018] Trial 4 finished with value: 0.811518341502547 and parameters: {'analyzer': 'word', 'word_ngram_max': 1, 'min_df': 2, 'max_df': 0.95, 'sublinear_tf': True, 'C': 0.6618942066108161, 'class_weight': None}. Best is trial 1 with value: 0.8302693479362567.
[I 2026-09-24 14:11:03,276] Trial 5 finished with value: 0.8107463612096879 and parameters: {'analyzer': 'word', 'word_ngram_max': 1, 'min_df': 2, 'max_df': 1.0, 'sublinear_tf': True, 'C': 0.8659338008476785, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8302693479362567.
[I 2026-09-24 14:11:04,026] Trial 6 finished with value: 0.8303237764821045 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 3.4916894290724074, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8303237764821045.
[I 2026-09-24 14:11:05,472] Trial 7 finished with value: 0.8255296543264816 and parameters: {'analyzer': 'char_wb', 'char_ngram_max': 5, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 0.5931468139658299, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8303237764821045.
[I 2026-09-24 14:11:06,158] Trial 8 finished with value: 0.8306489847158822 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 1.620805763690763, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.8306489847158822.
[I 2026-09-24 14:11:06,874] Trial 9 finished with value: 0.8278366141710609 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': True, 'C': 0.805566646692527, 'class_weight': None}. Best is trial 8 with value: 0.8306489847158822.
[I 2026-09-24 14:11:07,326] Trial 10 finished with value: 0.822785559091017 and parameters: {'analyzer': 'word', 'word_ngram_max': 2, 'min_df': 2, 'max_df': 0.95, 'sublinear_tf': False, 'C': 2.3387895825120433, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.8306489847158822.
[I 2026-09-24 14:11:08,038] Trial 11 finished with value: 0.8300604846704791 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 2.8229836109373116, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.8306489847158822.
[I 2026-09-24 14:11:08,743] Trial 12 finished with value: 0.8300402649351444 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 3.466986840914453, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.8306489847158822.
[I 2026-09-24 14:11:09,437] Trial 13 finished with value: 0.8312084834275126 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 1.6941686858080556, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:09,873] Trial 14 finished with value: 0.8295424124113762 and parameters: {'analyzer': 'word', 'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 1.7141097991806657, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:10,582] Trial 15 finished with value: 0.8301629304583621 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 1.4595533188463974, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:11,311] Trial 16 finished with value: 0.8289550852313268 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 7.19178185166221, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:11,782] Trial 17 finished with value: 0.8286055531652501 and parameters: {'analyzer': 'word', 'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 4.517206686000975, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:13,351] Trial 18 finished with value: 0.8190808868142122 and parameters: {'analyzer': 'char_wb', 'char_ngram_max': 5, 'min_df': 2, 'max_df': 1.0, 'sublinear_tf': False, 'C': 1.7387848920331683, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:14,007] Trial 19 finished with value: 0.8294843759894995 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 1.1332759273088038, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:14,259] Trial 20 finished with value: 0.8070708541731335 and parameters: {'analyzer': 'word', 'word_ngram_max': 1, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 2.076731967091883, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:15,000] Trial 21 finished with value: 0.8287568457918549 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 4.35672028279232, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:15,672] Trial 22 finished with value: 0.8302439096056402 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 3.0001504828550343, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:16,382] Trial 23 finished with value: 0.8291328821584575 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 4.679941906083612, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:17,073] Trial 24 finished with value: 0.8300604846704791 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 2.4342900845812494, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:17,732] Trial 25 finished with value: 0.8294843759894995 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 1.1308897460906349, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:19,928] Trial 26 finished with value: 0.8123022293604436 and parameters: {'analyzer': 'char_wb', 'char_ngram_max': 6, 'min_df': 2, 'max_df': 1.0, 'sublinear_tf': True, 'C': 3.6296676541500243, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:20,598] Trial 27 finished with value: 0.829779572591543 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 1.8070515446265372, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:20,840] Trial 28 finished with value: 0.8120294147372533 and parameters: {'analyzer': 'word', 'word_ngram_max': 1, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 0.48371184275486445, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:23,349] Trial 29 finished with value: 0.8130152913945075 and parameters: {'analyzer': 'char_wb', 'char_ngram_max': 6, 'min_df': 1, 'max_df': 1.0, 'sublinear_tf': False, 'C': 5.698917707460355, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:23,835] Trial 30 finished with value: 0.8195801768984203 and parameters: {'analyzer': 'word', 'word_ngram_max': 2, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 0.25022720618904526, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:24,583] Trial 31 finished with value: 0.8299862227444528 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 1.2496496531199432, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:25,346] Trial 32 finished with value: 0.8299441684939257 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 0.9298890778956909, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:26,149] Trial 33 finished with value: 0.8308644975858446 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 1.5012346028777819, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:26,895] Trial 34 finished with value: 0.8310466591509134 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 1.470989415585441, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:28,579] Trial 35 finished with value: 0.818909516906837 and parameters: {'analyzer': 'char_wb', 'char_ngram_max': 5, 'min_df': 1, 'max_df': 1.0, 'sublinear_tf': True, 'C': 1.465360757374345, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:29,127] Trial 36 finished with value: 0.8233630951912548 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 2, 'max_df': 0.95, 'sublinear_tf': False, 'C': 1.5252168780336064, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:29,881] Trial 37 finished with value: 0.8289027573963308 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': True, 'C': 2.0234240537026498, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:30,407] Trial 38 finished with value: 0.8257230902980457 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 2, 'max_df': 1.0, 'sublinear_tf': False, 'C': 0.953246838247027, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:32,056] Trial 39 finished with value: 0.8210789897490894 and parameters: {'analyzer': 'char_wb', 'char_ngram_max': 6, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': True, 'C': 0.3723374999350275, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:32,715] Trial 40 finished with value: 0.8283824326802464 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 0.7335842020601189, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:33,452] Trial 41 finished with value: 0.8299862227444528 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 1.2492641023297624, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:34,208] Trial 42 finished with value: 0.830269224694103 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 2.499342755184715, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:34,547] Trial 43 finished with value: 0.8119254419346348 and parameters: {'analyzer': 'word', 'word_ngram_max': 1, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 1.024309603018773, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:35,267] Trial 44 finished with value: 0.8300334071907225 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 2.127462330155895, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:36,015] Trial 45 finished with value: 0.8308074045513854 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 2.8872526588812106, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:36,748] Trial 46 finished with value: 0.8308074045513854 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': False, 'C': 2.869977537777016, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:37,013] Trial 47 finished with value: 0.8011289564109484 and parameters: {'analyzer': 'word', 'word_ngram_max': 1, 'min_df': 2, 'max_df': 0.95, 'sublinear_tf': False, 'C': 2.828811279561453, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:37,735] Trial 48 finished with value: 0.8284102402253828 and parameters: {'analyzer': 'word', 'word_ngram_max': 3, 'min_df': 1, 'max_df': 0.95, 'sublinear_tf': True, 'C': 3.375344016156858, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.
[I 2026-09-24 14:11:39,278] Trial 49 finished with value: 0.8221426267045073 and parameters: {'analyzer': 'char_wb', 'char_ngram_max': 5, 'min_df': 1, 'max_df': 1.0, 'sublinear_tf': False, 'C': 1.3779440919297818, 'class_weight': None}. Best is trial 13 with value: 0.8312084834275126.

Parameter Optuna terbaik: {'tfidf__analyzer': 'word', 'tfidf__ngram_range': (1, 3), 'tfidf__min_df': 1, 'tfidf__max_df': 0.95, 'tfidf__sublinear_tf': False, 'svm__C': 1.6941686858080556, 'svm__class_weight': 'balanced'}
Macro-F1 CV terbaik: 0.8312

--- Evaluasi SVM Optuna (holdout test set) ---
Accuracy    : 0.8670
Macro F1    : 0.8380
Weighted F1 : 0.8648
              precision    recall  f1-score   support

      defend       0.81      0.67      0.73       188
     neutral       0.86      0.91      0.88       419
      offend       0.89      0.90      0.90       513

    accuracy                           0.87      1120
   macro avg       0.85      0.83      0.84      1120
weighted avg       0.87      0.87      0.86      1120

Model tersimpan: C:\Users\andyc\Documents\a_skripsi\training\prethesis\ai_2_dataset_baru\models\intent_classifier_svm_optuna.pkl
Parameter terbaik: {'tfidf__analyzer': 'word', 'tfidf__ngram_range': (1, 3), 'tfidf__min_df': 1, 'tfidf__max_df': 0.95, 'tfidf__sublinear_tf': False, 'svm__C': 1.6941686858080556, 'svm__class_weight': 'balanced'}
Riwayat eksperimen: C:\Users\andyc\Documents\a_skripsi\training\prethesis\ai_2_dataset_baru\models\optuna_results\svm_8yb3t1uw

RINGKASAN EVALUASI HOLDOUT OPTUNA:

,model,accuracy_holdout,macro_f1_holdout,weighted_f1_holdout,macro_f1_cv,std_f1_cv,jumlah_trial,waktu_detik
0,Naive Bayes Optuna,0.8473,0.8171,0.8468,0.8166,0.011071,50,15.6
1,SVM Optuna,0.8670,0.8380,0.8648,0.8312,0.007162,50,44.3

HASIL CHAT UJI OPTUNA:

,model,chat,expected,predicted,confidence_persen,benar
0,Naive Bayes Optuna,B kena Gag Order ketika mulai ditanya alibinya...,offend,offend,61.58,True
1,Naive Bayes Optuna,Aku bukan Hitman. Tuduhan itu tidak punya bukt...,defend,defend,47.49,True
2,Naive Bayes Optuna,"Aku Spy dan semalam Guard Raka, jadi jangan cu...",defend,neutral,40.87,False
3,Naive Bayes Optuna,"Stalker, kamu Peek siapa semalam dan apa hasil...",neutral,neutral,62.99,True
4,Naive Bayes Optuna,Jangan hanya fokus ke aku; cek D yang ceritany...,offend,offend,52.58,True
5,Naive Bayes Optuna,"Vote C saja, dia paling diuntungkan ketika ses...",offend,offend,58.61,True
6,Naive Bayes Optuna,"Klaimku Civilian, jadi aku memang tidak memili...",defend,neutral,44.48,False
7,Naive Bayes Optuna,"Malam ini chat terkunci, kita lanjut diskusi s...",neutral,neutral,53.69,True
8,Naive Bayes Optuna,A selalu menghindar saat kita tanya kenapa dia...,offend,offend,68.60,True
9,Naive Bayes Optuna,Diamku bukan pengakuan; aku masih bisa menjela...,defend,neutral,42.89,False
10,SVM Optuna,B kena Gag Order ketika mulai ditanya alibinya...,offend,offend,96.22,True
11,SVM Optuna,Aku bukan Hitman. Tuduhan itu tidak punya bukt...,defend,defend,93.97,True
12,SVM Optuna,"Aku Spy dan semalam Guard Raka, jadi jangan cu...",defend,defend,66.50,True
13,SVM Optuna,"Stalker, kamu Peek siapa semalam dan apa hasil...",neutral,neutral,97.84,True
14,SVM Optuna,Jangan hanya fokus ke aku; cek D yang ceritany...,offend,offend,79.74,True
15,SVM Optuna,"Vote C saja, dia paling diuntungkan ketika ses...",offend,offend,96.80,True
16,SVM Optuna,"Klaimku Civilian, jadi aku memang tidak memili...",defend,neutral,77.49,False
17,SVM Optuna,"Malam ini chat terkunci, kita lanjut diskusi s...",neutral,neutral,82.25,True
18,SVM Optuna,A selalu menghindar saat kita tanya kenapa dia...,offend,offend,98.53,True
19,SVM Optuna,Diamku bukan pengakuan; aku masih bisa menjela...,defend,neutral,60.74,False

                model  jumlah_benar  jumlah_chat  akurasi
0  Naive Bayes Optuna             7           10      0.7
1          SVM Optuna             8           10      0.8